[jenkins]
<Jenkins-Private-IP-Address>

[nginx]
<Nginx-Private-IP-Address>

[sonar]
172.31.16.117 ansible_ssh_user='ubuntu'

[artifactory]
172.31.30.4  ansible_ssh_user='ec2-user'


[db]
172.31.81.94 ansible_ssh_user='ubuntu'